<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-27T00:01:02 IST" name="Suite" finished-at="2023-12-27T00:01:53 IST" duration-ms="50844">
    <groups>
    </groups>
    <test started-at="2023-12-27T00:01:02 IST" name="Test" finished-at="2023-12-27T00:01:53 IST" duration-ms="50844">
      <class name="qa.testcases.User_Test">
        <test-method is-config="true" signature="createPageObject()[pri:0, instance:qa.testcases.User_Test@4a335fa8]" started-at="2023-12-27T00:01:15 IST" name="createPageObject" finished-at="2023-12-27T00:01:15 IST" duration-ms="24" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPageObject -->
        <test-method signature="openUserPage()[pri:0, instance:qa.testcases.User_Test@4a335fa8]" started-at="2023-12-27T00:01:15 IST" name="openUserPage" finished-at="2023-12-27T00:01:18 IST" duration-ms="3195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openUserPage -->
        <test-method signature="addUserDetails()[pri:0, instance:qa.testcases.User_Test@4a335fa8]" started-at="2023-12-27T00:01:18 IST" name="addUserDetails" finished-at="2023-12-27T00:01:32 IST" depends-on-methods="qa.testcases.User_Test.openUserPage" duration-ms="13863" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addUserDetails -->
        <test-method signature="validateUser()[pri:0, instance:qa.testcases.User_Test@4a335fa8]" started-at="2023-12-27T00:01:32 IST" name="validateUser" finished-at="2023-12-27T00:01:53 IST" depends-on-methods="qa.testcases.User_Test.addUserDetails" duration-ms="20473" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Employee name mismatch expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Employee name mismatch expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1066)
at org.testng.Assert.assertEquals(Assert.java:1030)
at qa.testcases.User_Test.validateUser(User_Test.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUser -->
      </class> <!-- qa.testcases.User_Test -->
      <class name="qa.testcases.Login_Test">
        <test-method is-config="true" signature="initialization(java.lang.String)[pri:0, instance:qa.testcases.Login_Test@485a3466]" started-at="2023-12-27T00:01:02 IST" name="initialization" finished-at="2023-12-27T00:01:12 IST" duration-ms="10558" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method is-config="true" signature="createPageObject()[pri:0, instance:qa.testcases.Login_Test@485a3466]" started-at="2023-12-27T00:01:13 IST" name="createPageObject" finished-at="2023-12-27T00:01:13 IST" duration-ms="33" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPageObject -->
        <test-method signature="login_Test()[pri:0, instance:qa.testcases.Login_Test@485a3466]" started-at="2023-12-27T00:01:13 IST" name="login_Test" finished-at="2023-12-27T00:01:15 IST" duration-ms="2614" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:qa.testcases.Login_Test@485a3466]" started-at="2023-12-27T00:01:53 IST" name="tearDown" finished-at="2023-12-27T00:01:53 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- qa.testcases.Login_Test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
